theme: minima
description: This is the description

# pages in the navigation area
header_pages:
  - about.md

# author metadata
author:
  name: Kao SI
  email: kaosi@um.edu.mo

google_analytics: UA-NNNNNNNN-N